### ISSUE TITLE
A way to run .exclude instead of .filter

### ISSUE THREAD

**Issue by SEJeff** [philipn/django-rest-framework-filters#10]
In the ORM you could do:

    >>> Beer.objects.exclude(vendor__name__icontains='Busch').filter(...)

It would be awesome to replicate this functionality here. Perhaps prefacing the filter with `__exclude` ie:

    http://some.serv.e.r/api/beers/?exclude__name__icontains='bud'

**Comment by tomprt** [comment]
This can be done like this
```python
class BeerFilter(FilterSet):
    name = AllLookupsFilter(name='name')
    exclude_name = AllLookupsFilter(name='name', exclude=True)

    class Meta:
        model = Beer
```
I've created a pull request that should fix a bug that prevents exclude from being propagated to the child filters.

Also, to make it less tedious you could use create a meta class to automatically generate the exclude filters.
It is also can be implemented in the FilterSet class, perhaps by adding a field to the Meta class, something like:
```python
class BeerFilter(FilterSet):
    name = AllLookupsFilter(name='name')
    vendor = AllLookupsFilter(name='name')

    class Meta:
        model = Beer
        exclude_filters = True
        exclude_prefix = '!'
        exclude_suffix = ''
        no exclude = ['vendor']
```

if @philipn thinks this enhancement is OK I think I can write it.

**Comment by SEJeff** [comment]
So with the exclude_suffix would you do something in the query such as:

name__startswith=!bob

To exclude name startswith bob

**Comment by philipn** [comment]
I'm not sure what syntax/format is best here, but my gut impression is that it might be best to *only* allow this to be done via a suffix/prefix format, rather than recommend it be done using an `exclude` keyword argument in the `FilterSet`.  If we allow both the keyword and the suffix/prefix syntax, this opens up two entirely different ways to exclude result sets, which could be confusing.  Of course, it may not be possible to not allow the keyword-style `exclude`, but I think our docs should probably only recommend one option here.

Does anyone have a problem with the proposal by @tomprt, with, say, '!' as the default exclude prefix?

**Comment by SEJeff** [comment]
Looks excellent to me and sounds totally reasonable.

**Comment by rpkilby** [comment]
I've started working on a PR for this, but would anyone object to changing the syntax to
`name__startswith!=Bob`? Essentially, change it from a value prefix to a param suffix.

- Allows you to combine both a filter and exclude, since the param names wouldn't clash. (filter for articles containing 'Hello' in the title, but exclude those containing 'world'.

    ```http
    /api/articles?title__contains=Hello&title__contains!=World
    ```
- It *is* valid to search for exclamation marks.

**Comment by philipn** [comment]
I definitely prefer the `k!=v` syntax!  Also makes parsing a bit easier, I suspect.

**Comment by SEJeff** [comment]
Thanks! Can a pypi release be made with this new functionality?

**Comment by philipn** [comment]
@SEJeff Just pushed out `0.6.0` to PyPI

**Comment by SEJeff** [comment]
@philipn for president! Much appreciated.
