### ISSUE TITLE
Fix the formatting on PyPI

### ISSUE THREAD

**Issue by hedleyroos** [philipn/django-rest-framework-filters#165]
Not really an issue but it will make the product appear more professional on PyPI. Do `setup.py check --restructuredtext -s` to ensure the readme is in PyPI format.

**Comment by rpkilby** [comment]
My guess is that it's the addition of the `.. code-block:: http` blocks.

**Comment by rpkilby** [comment]
The markup is technically valid - it's probably due to pygments not supporting http.

**Comment by rpkilby** [comment]
It turns out that both pygments and linguist have `http` lexers, but they're intended for request messages, not just the URIs. 

Pygments is also a little more strict in that you'd need to use a correct request-line.

```http
GET /api/users?foo=bar HTTP/1.1
```

With linguist, you can get by with the below, which is technically invalid.

```http
GET https://localhost/api/users?foo=bar
```

**Comment by rpkilby** [comment]
It turns out that PyPI will automatically use the package's README if the setup script is missing a `long_description`. However, the check command doesn't have the same behavior, hence the erroneous success. Step one is to read in the REAMDE and set the `long_description`.

As to the actual rendering error, it had nothing to do with pygments and the http blocks. Docutils was complaining about line 339, which contains ``` ``FilterSet``s ```. The solution to just escape the 's'. ``` ``FilterSet``\s ```.
