### ISSUE TITLE
reverse relationship lookup support

### ISSUE THREAD

**Issue by rustanacexd** [philipn/django-rest-framework-filters#206]
does this support reverse relationship lookup?

**Comment by rpkilby** [comment]
yes

**Comment by rpkilby** [comment]
If you're having difficulty setting up the relationship, my first guess would be that you're using the related accessor name instead of the related query name. 

For example, if we have a simple Author <- Book model such as...

```python
class Author(models.Model):
    pass

class Book(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
```

In order to access the author's books, you'd normally do 
```python
author.book_set.all()
```

However, if you're filtering an author by the book relationship, the default related query name is just `book`. 

```python
Author.objects.filter(book__title__contains='...')
```

The reverse filter relationship would expect the query name, not the accessor name.
