### ISSUE TITLE
ComplexFilter with python 2.7

### ISSUE THREAD

**Issue by amcorreia** [philipn/django-rest-framework-filters#229]
I was trying to use ComplexFilter but I can't upgrade right now my project to python 3, is there possible to use OR in filter in v0.10.2 ?

**Comment by rpkilby** [comment]
Hi @amcorreia - can you be more specific?

**Comment by amcorreia** [comment]
Hi @rpkilby,

I want to be able to do:
```
field1=value1 | field2 = value2
```

Using v0.10.2 with python 2.7.

**Comment by rpkilby** [comment]
Unfortunately, there's no trivial way to setup OR filtering across multiple fields. django-filter chains the filter calls together, which is always an AND operation. 

If you only need to OR two fields together, then your best bet is to setup a filter based on a MultiValueField (e.g., RangeFilter), and then use a custom filter method to construct your OR query.

I'm closing this since there's no actual bug, but feel free to keep asking questions below.
