### ISSUE TITLE
Complex Filters from APIView

### ISSUE THREAD

**Issue by Svenito** [philipn/django-rest-framework-filters#305]
Hi,

I'm trying to add the complex filters to my view, but without success.

My Filter:

```
class JobFilter(filters.FilterSet):
    class Meta:
        model = Job
        fields = {
            'id': '__all__',
        }
```

and my view (for get)

```
class JobList(APIView):
    filter_class = JobFilter
    def get(self, request, format=None):
        print(request.GET)
        filter = JobFilter(request.GET, queryset=Job.objects.all())
        print(filter.filter_queryset(request.GET))
```

But the `filter.filter_queryset(request.GET)` always returns all objects and `filter.get_request_filters()` is an empty OrderedDict.

I can't find any examples with using the complex filters with a basic APIView and am a bit stuck. I need the basic view as I need to override the GET and POST methods.

Originally I am returning the results with:

```
jobs = Job.objects.all()
serialiser = JobSerialiser(jobs, many=True)
return Response(serialiser.data)
```

I'm reaching it via

`localhost:8000/jobs?filters=(id__gt=3)`

using Postman

[Django: 2.2.3 - DRFF: 1.0.0-dev0- Python 3.7.3]

Thanks in advance

**Comment by rpkilby** [comment]
Hi @Svenito. The short version is that view isn't using the `ComplexFilterBackend`, and in order to use complex filtering, you need to use the backend.

More generally, DRF filter backends are designed to work with `GenericAPIView`s, not `APIView`s. The difference being that `GenericAPIView` has machinery that works with the ORM, while the latter does not. You need to inherit `GenericAPIView`, but there are several other parts that you're missing. 

I'd recommend reading the DRF tutorial, but specifically [the CBV section](https://www.django-rest-framework.org/tutorial/3-class-based-views/) which helps explain `APIView` vs `GenericAPIView`. I'd also read the [generic views](https://www.django-rest-framework.org/api-guide/generic-views/) API guide. After that, take a look at our docs section on [configuring the `ComplexFilterBackend`](https://github.com/philipn/django-rest-framework-filters#configuring-complexfilterbackend).

Happy to answer more questions once you've gone over that.

**Comment by rjsnh1522** [comment]
Hi,
I have almost similar requirements. I am using ModelViewSet but i cant assign filter_class = MyFilterClass as I have to fetch data from different databases having same model structure.
After that I want to apply filter manually but its not working. I tried serializing the data and it gave me error that its not iterable. 
I did something like this
```
my_model_data = MyModel.objects.using(db_name).all() 
filtered_data = MyFilter(self.request.GET, queryset=my_model_data)
MySerializer(filtered_data, many=True).data
```

this will be done in a loop and the serialized data is appended in a list.
can you please tell me how to apply the filters manually.

**Comment by rpkilby** [comment]
Hi @rjsnh1522. The `FilterSet` isn't itself iterable (you wouldn't pass it to the serializer). Instead, you want to access the filtered queryset. Something like:

```python
my_model_data = MyModel.objects.using(db_name).all() 
my_filter_set = MyFilter(self.request.GET, queryset=my_model_data)
MySerializer(my_filter_set.qs, many=True).data
```
