### ISSUE TITLE
compatible with django_model_utils Choices

### ISSUE THREAD

**Issue by dbinetti** [philipn/django-rest-framework-filters#78]
I am using @carljm's django_model_util Choices field.  is this package compatible?  i ask because i am trying to create a filter that uses the human-readable version of the choices field backing a model field, and can't get it to work.  if it is compatible, i'd love a concrete example to follow.  thanks...

**Comment by rpkilby** [comment]
Hi @dbinetti. Looking over the code, the choices field is just a regular `CharField` that pulls its choices from the parent model, so it would exhibit the same characteristics as the underlying field. 

What are you're trying to accomplish by using the human-readable value instead of the code value? Could you provide a concrete example? 

Using the human-readable value is generally problematic, as this is a display value subject to transformation (language translation, capitalization, etc...). The code values are more durable since they aren't transformed.

**Comment by dbinetti** [comment]
I'm trying to make the URL human readable (and fungible directly).  However, your point about transformation makes good sense.   I'll let this go.

**Comment by rpkilby** [comment]
I'd say your best bet is to use code values that are human friendly. 

eg,
```py
# Use:
STATUSES = (
    ('started', 'Started'),
    ('in_progress', 'In Progress'),
    ('finished', 'Finished'),
    ('errored', 'Errored'),
)

# instead of
STATUSES = (
    ('s', 'Started'),
    ('p', 'In Progress'),
    ('f', 'Finished'),
    ('e', 'Errored'),
)

**Comment by dbinetti** [comment]
actually, i'm using integers (order is important)  motel_utils allow for a
three-tuple (1,'foo', 'Foo Bar'), so that would potentially work, but i
think i'll just work things on the front end appropriately.

tks
