### ISSUE TITLE
neither contains or icontains is working

### ISSUE THREAD

**Issue by ericntd** [philipn/django-rest-framework-filters#88]
My `/api/articles/` returns 100 results.
Both `/api/articles/title__contains=Hot` and `/api/articles/title__icontains` return 100 results.
Negation is working.
Exact match is working.
My ViewSet is as follows:
```python
import rest_framework_filters as rf_filters
from rest_framework import filters

class ArticleFilterRf(rf_filters.FilterSet):
    category = rf_filters.CharFilter(name="cat__slug")
    category_id = rf_filters.CharFilter(name="cat_id")

    class Meta:
        model = Article
        fields = ['id', 'status', 'category', 'category_id', 'deleted', 'author', 'featured', 'tags', 'title']
class ArticleViewSet(viewsets.ModelViewSet):
    """
    A viewset for viewing and editing user instances.
    """
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = ArticleSerializer
    queryset = Article.objects.all()
    filter_backends = (filters.SearchFilter, filters.DjangoFilterBackend, filters.OrderingFilter,)
    search_fields = ('title', 'tags', 'slug', 'status', 'cat__title', 'cat__slug', 'author')
    filter_class = ArticleFilterRf
    ordering_fields = ('title', 'updated')
    ordering = ('updated',)
```

**Comment by rpkilby** [comment]
Hi @ericntd. There is both a list syntax and dict syntax for `Meta.fields`. The list syntax only creates filters for the `exact` lookup. You should be using the dict syntax instead. 

Also, make sure to use the `rest_framework_filters.backends.DjangoFilterBackend` backend instead of the default backend.

**Comment by jsmedmar** [comment]
does the icontains filter works for a related (ForeingKey) relationship? Wondering why it isnt working for me...

**Comment by jsmedmar** [comment]
I'll add more details later today.

**Comment by rpkilby** [comment]
icontains does not work on a foreign key value, although it will work across relationships on a foreign field.

icontains isn't a registered lookup for FKs:
https://github.com/django/django/blob/master/django/db/models/fields/related_lookups.py

**Comment by jsmedmar** [comment]
I didn't get this part though:

> although it will work across relationships on a foreign field

**Comment by rpkilby** [comment]
For example:
```py
class AuthorFilter(FilterSet):
    class Meta:
        model = Author
        fields = {'username': ['icontains']}

class BookFilter(FilterSet):
    author = RelatedFilter(AuthorFilter)

   class Meta:
        model = Book
```

You could do `/books?author__username__icontains=bob`. You can traverse the author FK and do an icontains on a related field.

**Comment by jsmedmar** [comment]
Is there a way to do a symlink to a field of a `RelatedFilter`? something like:


```python
class AuthorFilter(FilterSet):
    class Meta:
        model = Author
        fields = {'username': ['icontains']}

class BookFilter(FilterSet):
    username = RelatedFilter(AuthorFilter, name="username")

   class Meta:
        model = Book
```

**Comment by jsmedmar** [comment]
I just don't want the client to know that they are actually querying a related model, that is not relevant to them.

**Comment by rpkilby** [comment]
I'm not sure if it will work, but you might be able to do...

```py
class BookFilter(FilterSet):
    author = RelatedFilter(AuthorFilter, name="author__username")
```

**Comment by jsmedmar** [comment]
Ok, it didn't work... I'll think more about it

**Comment by jsmedmar** [comment]
I just realized that this [solution](https://github.com/philipn/django-rest-framework-filters/issues/88#issuecomment-234356829) does not work... You cannot traverse the author FK and do an icontains on a related field.

**Comment by rpkilby** [comment]
You should be able to filter on related model fields. See [this](https://github.com/philipn/django-rest-framework-filters/blob/v0.8.0/tests/test_filterset.py#L178-L184) as an example - it's the same idea.

The name aliasing - not so sure about that. I'll try to look into it further.

**Comment by jsmedmar** [comment]
I think there might be an issue with this [test case](https://github.com/philipn/django-rest-framework-filters/blob/v0.8.0/tests/test_filterset.py#L192-L196) though... If you do `contains=user` you will retrieve all your notes which are 4 (all 4 notes were written by `user1` and `user2`) and there is the catch. When I try to implement this same setting, if I use `contains`, I'm getting back the entire queryset regardless the value I'm filtering against (and that is why your test is passing). I think if we change that test for `contains=1`, it will fail because it will expect 2 but it will get 4. If I do `icontains` I'm getting an empty queryset. 

What is interesting however, is `endswith` doesn't work for me neither...

**Comment by jsmedmar** [comment]
I just get empty querysets if I don't put the exact value, for example:

```python
len(list(NoteFilter({"author__username__icontains": "u"}, queryset=Note.objects.all()))) = 0
len(list(NoteFilter({"author__username__icontains": "user1"}, queryset=Note.objects.all()))) = 2
```

**Comment by jsmedmar** [comment]
Ok I think I found the problem...

icontains does not work in fields that have choices (`analyte`) but it does work on fields without choices (`ext_id`):

```python
class Extraction(Model):

    analyte = models.CharField(
        verbose_name=_("Biological Material"),
        max_length=100,
        choices=CHOICES,
        null=True,
        )

    ext_id = models.CharField(
        verbose_name=_("Extraction External ID"),
        max_length=100,
        blank=True,
        default=None,
        )
```

Is this an expected behavior?

**Comment by rpkilby** [comment]
> does not work with fields that have choices

Great catch! This [if statement](https://github.com/carltongibson/django-filter/blob/v0.13/django_filters/filterset.py#L490-L491) has been nagging me for a very long time but decided to just leave it be. The problem is that the value being filtered won't match any of the choices, so it won't validate and returns 0 results. I've submitted a PR (carltongibson/django-filter#447) to only create choice filters for exact lookups (which was probably the original intent anyway).

The following should get around this. Not a great solution, but it *should* work.
```py
class FilterSet(filters.FilterSet):

    @classmethod
    def filter_for_lookup(cls, f, lookup_type):
        # copy field and remove choices to bypass default behavior
        # See: https://github.com/carltongibson/django-filter/issues/447
        if f.choices and lookup_type != 'exact':
            f = deepcopy(f)
            f.choices = None

        return super(FilterSet, cls).filter_for_lookup(f, lookup_type)
            
```

**Comment by jsmedmar** [comment]
@rpkilby hey! thank you very much, so I saw that django-filters merged your pull request. Thats great. I think I'll create a new "issue" for the field aliasing, I think that would be a nice feature for django-rest-framework-filters
