### ISSUE TITLE
ManyToMany Filters Duplicated Query

### ISSUE THREAD

**Issue by jsmedmar** [philipn/django-rest-framework-filters#91]
Hello,

Imagine this very simple example of Dogs that have Human enemies and Human friends:

```
model Human:

    name: CharField()

model Dog:

    friends:  ManyToMany(Human)
    enemies: ManytToMany(Human)

filter DogFilter:

    friends: Filter(name="friends")
    enemies: Filter(name="ennemies")
```

When I hit the API the filter class performs a duplicated query `select all Humans` one time for the field `friends` another time for the field `enemies`.

I have two questions:

    1. is it possible to cache a duplicated query?
    2. Why does these queries happen even when I do not filter at all in the API?

Let me know if you need more clarification.

**Comment by rpkilby** [comment]
Hi @jsmedmar. I would need more information to provide a better answer, but my guess is that the browsable API renderer is rendering your filterset as a form. The form includes the friends/enemies m2m filters, which is getting its choices by querying the humans table. 

1. There is no immediately obvious solution for caching duplicate queries in the filterset. It might be better to cache your queries per request in Django?
2. Try viewing the API as a JSON response instead of through the browsable API renderer. The filterset shouldn't be rendered, so the queries should happen.

**Comment by jsmedmar** [comment]
That is a great answer! I think that is actually the case :) Caching isnt needed because that duplicate comes from the filterset rendering. Thank you very much.
